jwt:
  secret: "secret123456789"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/archi_v1
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
